f <- getwd()
script.dir <- dirname(parent.frame(2)$ofile)
setwd(script.dir)
mkdir <- function(x)
{
	dir.create(file.path(x), showWarnings = FALSE)
}
fcopy <- function(x,y,z,w)
{
	file.link(file.path(x,y),file.path(z,w))
	file.rename(from=file.path(x,y),to=file.path(y,z))
}
crdir <- function()
{
	mkdir('TEST')
	mkdir('TRAIN')
	mkdir('TEST/data_ext')
	mkdir('TRAIN/data_ext')
	mkdir('TEST/trends')
	mkdir('TRAIN/trends')
}
copy <- function()
{
	fcopy('INPUT','action_test.R','TEST','action.R')
	fcopy('INPUT','action_train.R','TRAIN','action.R')
	fcopy('INPUT','data1_test.csv','TEST/trends','data1.csv')
	fcopy('INPUT','data1_train.csv','TRAIN/trends','data1.csv')
	fcopy('INPUT','data2_test.csv','TEST/trends','data2.csv')
	fcopy('INPUT','data2_train.csv','TRAIN/trends','data2.csv')
	fcopy('INPUT','data3_test.csv','TEST/data_ext','data3.csv')
	fcopy('INPUT','data3_train.csv','TRAIN/data_ext','data3.csv')
	fcopy('INPUT','boxoffice.R','TRAIN/data_ext','boxoffice.R')
	fcopy('INPUT','boxoffice.R','TEST/data_ext','boxoffice.R')
	fcopy('INPUT','databindings.R','TRAIN/data_ext','databindings.R')
	fcopy('INPUT','databindings.R','TEST/data_ext','databindings.R')
	fcopy('INPUT','movie_separation.R','TRAIN/data_ext','movie_separation.R')
	fcopy('INPUT','movie_separation.R','TEST/data_ext','movie_separation.R')
	fcopy('INPUT','generateq0toq6.R','TRAIN/data_ext','generateq0toq6.R')
	fcopy('INPUT','generateq0toq6.R','TEST/data_ext','generateq0toq6.R')
	fcopy('INPUT','trends.R','TRAIN/trends','trends.R')
	fcopy('INPUT','trends.R','TEST/trends','trends.R')
	fcopy('INPUT','trends2.R','TRAIN/trends','trends2.R')
	fcopy('INPUT','trends2.R','TEST/trends','trends2.R')
	fcopy('INPUT','photos.R','TRAIN/trends','photos.R')
	fcopy('INPUT','photos.R','TEST/trends','photos.R')
	fcopy('INPUT','generatep0top6.R','TRAIN/trends','generatep0top6.R')
	fcopy('INPUT','generatep0top6.R','TEST/trends','generatep0top6.R')
}
sourceMe <- function()
{
	# source('TRAIN/data_ext/boxoffice.R')
	# source('TRAIN/data_ext/databindings.R')
	# source('TRAIN/data_ext/movie_separation.R')
	source('TRAIN/data_ext/generateq0toq6.R')
	# source('TRAIN/trends/trends.R')
	# source('TRAIN/trends/trends2.R')
	# source('TRAIN/trends/photos.R')
	source('TRAIN/trends/generatep0top6.R')
	source('TRAIN/action.R')
	setwd('..')
	setwd('..')
	# source('TEST/data_ext/boxoffice.R')
	# source('TEST/data_ext/databindings.R')
	# source('TEST/data_ext/movie_separation.R')
	source('TEST/data_ext/generateq0toq6.R')
	# source('TEST/trends/trends.R')
	# source('TEST/trends/trends2.R')
	# source('TEST/trends/photos.R')
	source('TEST/trends/generatep0top6.R')
	source('TEST/action.R')
	setwd('..')
	setwd('..')
	#source("http://bioconductor.org/biocLite.R")
	#biocLite("Biobase")
	library('Biobase')
	openPDF(normalizePath("TRAIN/first_rel.pdf"))
	openPDF(normalizePath("TRAIN/est_rel0.pdf"))
	openPDF(normalizePath("TRAIN/est_rel1.pdf"))
	openPDF(normalizePath("TRAIN/est_rel2.pdf"))
	openPDF(normalizePath("TRAIN/est_rel3.pdf"))
	openPDF(normalizePath("TRAIN/est_rel4.pdf"))
	openPDF(normalizePath("TRAIN/predict_max_train.pdf"))
	openPDF(normalizePath("TRAIN/predict_min_train.pdf"))
	openPDF(normalizePath("TRAIN/predict_mean_train.pdf"))
	openPDF(normalizePath("TEST/first_rel_test.pdf"))
	openPDF(normalizePath("TEST/est_rel0_test.pdf"))
	openPDF(normalizePath("TEST/est_rel1_test.pdf"))
	openPDF(normalizePath("TEST/est_rel2_test.pdf"))
	openPDF(normalizePath("TEST/est_rel3_test.pdf"))
	openPDF(normalizePath("TEST/est_rel4_test.pdf"))
	openPDF(normalizePath("TEST/predict_max_test.pdf"))
	openPDF(normalizePath("TEST/predict_min_test.pdf"))
	openPDF(normalizePath("TEST/predict_mean_test.pdf"))
	
	
}
execute <- function()
{
	cat('\014')
	crdir()
	copy()
	sourceMe()
}
setwd(f)